service: space-service-api

frameworkVersion: ^2.11.0

plugins:
  - serverless-dotenv-plugin
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-plugin-monorepo
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  memorySize: 512
  stage: ${opt:stage}
  profile: picnic
  environment:
    SENTRY_ENVIRONMENT: "${self:provider.stage}"
    SENTRY_DNS: "${env:SENTRY_DNS}"
    MONGO_DB_URL: "${env:MONGO_DB_URL}"
    DOMAIN: ${self:custom.sbs.domains.${opt:stage, self:provider.stage}}
    S3_IMAGE_BUCKET: ${self:custom.sbs.bucketName.${opt:stage, self:provider.stage}}
    API_SECRET: "${env:API_SECRET}"
    USER_SERVICE_API_SECRET: "${env:USER_SERVICE_API_SECRET}"
    MAX_POOL_SIZE: ${env:MAX_POOL_SIZE, 20}
    MIN_POOL_SIZE: ${env:MIN_POOL_SIZE, 2}
    POOL_SIZE: ${env:POOL_SIZE, 10}
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.sbs.bucketName.${opt:stage, self:provider.stage}}/*"

package:
  individually: false

functions:
  list:
    handler: src/handler.list
    events:
      - http:
          path: list
          method: get
          cors: ${file(./serverless/cors.yml):main}
  getSpace:
    handler: src/handler.getSpace
    events:
      - http:
          path: get
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminSpaceList:
    handler: src/handler.adminSpaceList
    events:
      - http:
          path: admin/space
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminSpaceUpdate:
    handler: src/handler.adminSpaceUpdate
    events:
      - http:
          path: admin/space/update
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminSpaceRemove:
    handler: src/handler.adminSpaceRemove
    events:
      - http:
          path: admin/space/remove
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminPollCreate:
    handler: src/handler.adminPollCreate
    events:
      - http:
          path: admin/poll/create
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminPollUpdate:
    handler: src/handler.adminPollUpdate
    events:
      - http:
          path: admin/poll/update
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminPollRemove:
    handler: src/handler.adminPollRemove
    events:
      - http:
          path: admin/poll/remove
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminVoterCreate:
    handler: src/handler.adminVoterCreate
    events:
      - http:
          path: admin/voter/create
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminVoterUpdate:
    handler: src/handler.adminVoterUpdate
    events:
      - http:
          path: admin/voter/update
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminVoterRemove:
    handler: src/handler.adminVoterRemove
    events:
      - http:
          path: admin/voter/remove
          method: post
          cors: ${file(./serverless/cors.yml):main}
  adminImageUpload:
    handler: src/handler.adminImageUpload
    events:
      - http:
          path: admin/image/upload
          method: post
          cors: ${file(./serverless/cors.yml):main}
  pollList:
    handler: src/handler.pollList
    events:
      - http:
          path: polls/list
          method: post
          cors: ${file(./serverless/cors.yml):main}
  getVote:
    handler: src/handler.getVote
    events:
      - http:
          path: polls/vote/get
          method: post
          cors: ${file(./serverless/cors.yml):main}
  getPollResult:
    handler: src/handler.getPollResult
    events:
      - http:
          path: polls/result
          method: post
          cors: ${file(./serverless/cors.yml):main}
  submitVote:
    handler: src/handler.submitVote
    events:
      - http:
          path: polls/vote/submit
          method: post
          cors: ${file(./serverless/cors.yml):main}

resources:
  Resources:
    ClientBucketResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.sbs.bucketName.${opt:stage, self:provider.stage}}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000
custom:
  sbs:
    bucketName:
      production: space-service-images-production
      staging: space-service-images-staging
      dev: space-service-images-staging
    domains:
      production: "space.sidebyside.live"
      staging: "space.dev.sidebyside.live"
      dev: "localhost"

  serverless-offline:
    useChildProcesses: true
    httpPort: 4000

  webpack:
    webpackConfig: "webpack.config.js"
    keepOutputDirectory: true
    includeModules: true
    packager: "yarn"
    excludeFiles: src/**/*.test.js

  stages:
    - dev
    - production
    - staging

  customDomain:
    domainName: ${self:custom.sbs.domains.${opt:stage, self:provider.stage}}
    stage: ${opt:stage}
    basePath: api
    certificateName: "*.sidebyside.live"
    createRoute53Record: true
    endpointType: "regional"
    apiType: rest
    autoDomain: true

  s3:
    host: localhost
    cors: ./serverless/cors-s3.xml
    allowMismatchedSignatures: true
